{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1e4d7d14-3e85-4468-a3cf-648b372c8592",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "import pandas as pd\n",
    "import logging\n",
    "from ingestion_db import ingest_db\n",
    "\n",
    "logging.basicConfig(\n",
    "    filename=\"logs?get_vendor_summary.log\",\n",
    "    level = logging.DEBUG,\n",
    "    format = \"%(asctime)s- %(levelname)s - %(message)s\",\n",
    "    filemode=\"a\"\n",
    ")\n",
    "\n",
    "def create_vendor_summary(conn):\n",
    "    '''this function will merge the different tables to get the overall vendor summary and adding new columns in the resultant data'''\n",
    "    vendor_sales_summary = pd.read_sql_query(\"\"\"WITH FreightSummary AS (\n",
    "        select\n",
    "            VendorNumber,\n",
    "            SUM(Freight) AS FreightCost\n",
    "        from vendor_invoice\n",
    "        GROUP BY VendorNumber\n",
    "    ),\n",
    "\n",
    "    PurchaseSummary AS (\n",
    "        SELECT \n",
    "            p.VendorNumber,\n",
    "            p.VendorName,\n",
    "            p.Brand,\n",
    "            p.Description,\n",
    "            p.PurchasePrice,\n",
    "            pp.Price as ActualPrice,\n",
    "            pp.Volume,\n",
    "            SUM(p.Quantity) AS TotalPurchaseQuantity,\n",
    "            SUM(p.Dollars) AS TotalPurchaseDollars\n",
    "            FROM purchases p\n",
    "            JOIN purchase_prices pp\n",
    "            ON p.Brand = pp.Brand\n",
    "            Where p.PurchasePrice > 0\n",
    "            Group By p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume\n",
    "        ),\n",
    "        \n",
    "        SalesSummary AS (\n",
    "            Select\n",
    "                VendorNo,\n",
    "                Brand,\n",
    "                SUM(SalesQuantity) AS TotalSalesQuantity,\n",
    "                SUM(SalesDollars) AS TotalSalesDollars,\n",
    "                SUM(SalesPrice) AS TotalSalesPrice,\n",
    "                SUM(ExciseTax) AS TotalExciseTax\n",
    "            From sales\n",
    "            Group BY VendorNo, Brand\n",
    "         )\n",
    "         \n",
    "         Select\n",
    "             ps.VendorNumber,\n",
    "             ps.VendorName,\n",
    "             ps.Brand,\n",
    "             ps.Description,\n",
    "             ps.Purchaseprice,\n",
    "             ps.ActualPrice,\n",
    "             ps.Volume,\n",
    "             ps.TotalPurchaseQuantity,\n",
    "             ps.TotalPurchaseDollars,\n",
    "             ss.TotalSalesQuantity,\n",
    "             ss.TotalSalesDollars,\n",
    "             ss.TotalSalesPrice,\n",
    "             ss.TotalExciseTax,\n",
    "             fs.FreightCost\n",
    "        FROM  PurchaseSummary ps\n",
    "        LEFT JOIN SalesSummary ss\n",
    "        ON ps.VendorNumber = ss.VendorNo\n",
    "        AND ps.Brand = ss.Brand\n",
    "        LEFT JOIN FreightSummary fs\n",
    "        ON ps.VendorNumber = fs.VendorNumber\n",
    "        ORDER BY ps.TotalPurchaseDollars DESC \"\"\", conn)\n",
    "\n",
    "    return vendor_sales_summary\n",
    "\n",
    "def clean_data(df):\n",
    "    '''this function will clean the data'''\n",
    "    #changing datatype to float\n",
    "    df['Volume'] = df['Volume'].astype('float')\n",
    "\n",
    "    #filling missing value with 0\n",
    "    df.fillna(0,inplace = TRUE)\n",
    "\n",
    "    #removing spaces from categorical columns\n",
    "    df['VendorName'] = df['VendorName'].str.strip()\n",
    "    df['Description'] = df['Description'].str.strip()\n",
    "\n",
    "    #creating new columns for better analysis\n",
    "    vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_analysis['TotalPurchaseDollars']\n",
    "    vendor_sales_summary['ProfitMargin'] = vendor_sales_summary['GrossProfit'] / vendor_sales_analysis['TotalSalesDollars']*100\n",
    "    vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_analysis['TotalPurchaseQuantity']\n",
    "    vendor_sales_summary['SalesPurchaseratio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_analysis['TotalPurchaseDollars']\n",
    "\n",
    "    return df\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    #creating database connection\n",
    "    conn = sqlite3.connect('inventory.db')\n",
    "    \n",
    "    logging.info('Creating Vendor Summary Table.....')\n",
    "    summary_df = create_vendor_summary(conn)\n",
    "    logging.info(summary_df.head())\n",
    "\n",
    "    logging.info('Cleaning Data.....')\n",
    "    clean_df = clean_data(summary_df)\n",
    "    logging.info(clean_df.head())\n",
    "\n",
    "    logging.info('Ingesting Data.....')\n",
    "    ingest_db (clean_df, 'vendor_sales_summary',(conn))\n",
    "    logging.info('Completed')\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
